services:

  wayfarer-auth:
    build:
      context: .
      dockerfile: ./apps/wayfarer-auth/Dockerfile
    container_name: wayfarer-auth
    env_file:
      - .env.docker
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/wayfarer-auth:/usr/src/app/apps/wayfarer-auth
      - /usr/src/app/node_modules
    networks:
      - wayfarer-network
    restart: always

  wayfarer-catalog:
    build:
      context: .
      dockerfile: ./apps/wayfarer-catalog/Dockerfile
    container_name: wayfarer-catalog
    env_file:
      - .env.docker
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/wayfarer-catalog:/usr/src/app/apps/wayfarer-catalog
      - /usr/src/app/node_modules
    networks:
      - wayfarer-network
    restart: always

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - .env.docker
    ports:
      - "9000:9000"
    depends_on:
      - wayfarer-auth
      - wayfarer-catalog
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
      - /usr/src/app/node_modules
    networks:
      - wayfarer-network
    restart: always

networks:
  wayfarer-network:
    driver: bridge
